nav:
  - Home: index.md
  - Introduction: intro.md
  - Quick Start: quickstart.md
  - Examples: examples.md
  - JSON:
    - Message format: json-format.md
    - Flowspec: flowspec.md
  - Filtering: filters.md
  - Stages:
    - Overview: stages/index.md
    - connect: stages/connect.md
    - drop: stages/grep.md
    - exec: stages/exec.md
    - grep: stages/grep.md
    - head: stages/head.md
    - limit: stages/limit.md
    - listen: stages/listen.md
    - pipe: stages/pipe.md
    - read: stages/read.md
    - ris-live: stages/ris-live.md
    - rpki: stages/rpki.md
    - rv-live: stages/rv-live.md
    - speaker: stages/speaker.md
    - stdin: stages/stdin.md
    - stdout: stages/stdout.md
    - tag: stages/tag.md
    - update: stages/update.md
    - websocket: stages/websocket.md
    - write: stages/write.md

site_name: "bgpipe: BGP pipeline processor"
site_url: 'https://bgpipe.org/'
repo_url: https://github.com/bgpfix/bgpipe

theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo-w.png
  features:
    - header.autohide
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: slate
      primary: purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      primary: purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode

extra:
  generator: false
  version:
    provider: mike
    alias: true

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true
