nav:
  - Home: index.md
  - Introduction: intro.md
  - Quick Start: quickstart.md
  - Stages:
    - Overview: stages/index.md
    - Connection:
      - connect: stages/connect.md
      - listen: stages/listen.md
      - speaker: stages/speaker.md
    - Input / Output:
      - stdin: stages/stdin.md
      - stdout: stages/stdout.md
      - read: stages/read.md
      - write: stages/write.md
    - Filtering:
      - grep / drop: stages/grep.md
      - tag: stages/tag.md
      - limit: stages/limit.md
    - Modification:
      - update: stages/update.md
    - External Processing:
      - exec: stages/exec.md
      - pipe: stages/pipe.md
      - websocket: stages/websocket.md
    - Live Streaming:
      - ris-live: stages/ris-live.md
      - rv-live: stages/rv-live.md
    - Security:
      - rpki: stages/rpki.md
  - Examples: examples.md
  - JSON Format: json-format.md
  - Message Filters: filters.md

site_name: "bgpipe: BGP reverse proxy"
site_url: 'https://bgpipe.org/'
repo_url: https://github.com/bgpfix/bgpipe

theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo-w.png
  features:
    - header.autohide
    - content.code.copy
    - content.code.annotate 
  palette:
    - scheme: slate
      primary: purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      primary: purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode

extra:
  generator: false
  version:
    provider: mike
    alias: true

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true
